import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "app.title": "Pet Nova",
    "app.subtitle": "Pet Care Community",
    "nav.weCare": "We Care",
    "nav.inMyPet": "In My Pet",
    "nav.action": "Action",
    "nav.smartCalendar": "Paw Planner",
    "nav.petMap": "Pet Map",
    "nav.viewProfile": "View Profile",
    "nav.myPets": "My Pets",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "nav.todo": "To Do",
    "nav.home": "Home",
    "nav.desinformacion": "Misinformation",
    "nav.desorganizacion": "Disorganization",
    "nav.alertaPaw": "Paw Alert",
    "nav.denunciasAnonimas": "Anonymous Reports",
    "nav.infoSite": "We Care",
    "nav.vaccinationDays": "Vaccination Days",
    "nav.myPetCommunity": "My Pet Community",
    "nav.petMoments": "Pet Moments",
    "todo.title": "To Do",
    "todo.subtitle": "Tasks to take care of",
    "todo.addPlaceholder": "New task...",
    "todo.dueDate": "Due date (optional)",
    "todo.add": "Add",
    "todo.all": "All",
    "todo.pending": "Pending",
    "todo.done": "Done",
    "todo.empty": "No tasks here.",
    "todo.clearDone": "Clear completed",
    "calendar.viewMonth": "Month",
    "calendar.viewList": "List",
    "calendar.filterAll": "All",
    "calendar.filterAppointments": "Appointments",
    "calendar.filterVaccines": "Vaccines",
    "calendar.filterReminders": "Reminders",
    "calendar.addReminder": "Add reminder",
    "calendar.reminderPlaceholder": "Reminder title...",
    "calendar.thisMonth": "This month",
    "calendar.noDay": "No events this day for",
    "theme.light": "Light mode",
    "theme.dark": "Dark mode",
    "login.welcome": "Welcome back",
    "login.subtitle": "Log in to Pet Nova",
    "login.email": "Email",
    "login.password": "Password",
    "login.rememberPassword": "Remember password",
    "login.submit": "Log In",
    "login.submitting": "Logging in...",
    "login.invalidCredentials": "Please enter a valid email and password",
    "login.welcomeToast": "Welcome back!",
    "login.failed": "Couldn't log in. Is the backend running?",
    "registration.title": "Join Pet Nova",
    "registration.subtitle": "Register your pet and yourself in under two minutes",
    "registration.step1": "Step 1 · Pet Profile",
    "registration.step2": "Step 2 · Medical Record",
    "registration.step3": "Step 3 · Owner Details",
    "registration.petName": "Pet's Name",
    "registration.species": "Species",
    "registration.age": "Age (years)",
    "registration.breed": "Breed",
    "registration.weight": "Weight",
    "registration.unit": "Unit",
    "registration.photo": "Photo",
    "registration.uploadPhoto": "Upload Photo",
    "registration.vaccinated": "Vaccinated?",
    "registration.disability": "Special Condition?",
    "registration.disabilityDetail": "Describe it",
    "registration.medicalNotes": "Medical Notes",
    "registration.ownerName": "Full Name",
    "registration.email": "Email",
    "registration.phone": "Phone",
    "registration.city": "City",
    "registration.next": "Next",
    "registration.back": "Back",
    "registration.register": "Register",
    "registration.haveAccount": "Already have an account?",
    "registration.loginLink": "Log in",
    "registration.password": "Password",
    "registration.confirmPassword": "Confirm Password",
    "registration.passwordPlaceholder": "At least 6 characters",
    "registration.confirmPasswordPlaceholder": "Repeat your password",
    "registration.passwordMinLength": "Password must be at least 6 characters",
    "registration.passwordMismatch": "Passwords don't match",
    "registration.emailExists": "An account with that email already exists",
    "registration.creatingAccount": "Creating account...",
    "authSwitch.login": "Log In",
    "authSwitch.register": "Create Account",
    "authSwitch.ariaLabel": "Switch between log in and create account",
    "dashboard.hello": "Hello",
    "dashboard.welcome": "Welcome to",
    "dashboard.panel": "panel",
    "dashboard.appointments": "Appointments",
    "dashboard.vaccines": "Vaccines",
    "dashboard.alerts": "Active Alerts",
    "dashboard.city": "City",
    "dashboard.scheduleAppointment": "Schedule Appointment",
    "dashboard.date": "Date",
    "dashboard.time": "Time",
    "dashboard.type": "Type",
    "dashboard.veterinarian": "Veterinarian",
    "dashboard.notes": "Notes",
    "dashboard.schedule": "Schedule",
    "dashboard.upcomingAppointments": "Upcoming Appointments",
    "dashboard.noAppointments": "No appointments scheduled",
    "dashboard.registerVaccine": "Register Vaccine",
    "dashboard.vaccineName": "Vaccine Name",
    "dashboard.applicationDate": "Application Date",
    "dashboard.nextDue": "Next Due",
    "dashboard.vaccineHistory": "Vaccine History",
    "dashboard.noVaccines": "No vaccines registered",
    "dashboard.createAlert": "Create Paw Alert",
    "dashboard.location": "Location",
    "dashboard.description": "Description",
    "dashboard.contact": "Your Contact",
    "dashboard.publishAlert": "Publish Alert",
    "dashboard.communityAlerts": "Community Alerts",
    "dashboard.noAlerts": "No active alerts",
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.email": "Email",
    "settings.password": "Password",
    "settings.preferences": "Preferences",
    "settings.theme": "Theme",
    "common.cancel": "Cancel",
    "settings.language": "Language",
    "settings.profile": "Profile",
    "settings.privacy": "Privacy",
    "settings.about": "About",
    "map.title": "Huellitas al Camino",
    "map.veterinarians": "Veterinarians",
    "map.parks": "Parks",
    "map.groomers": "Groomers",
    "map.lostPets": "Lost Pets",
    "toast.success": "Success",
    "toast.error": "Error",
    "toast.required": "Please fill in all required fields",
    "app.logoAlt": "Pet Nova - We care for what you love",
    "dashboard.overview": "Overview",
    "dashboard.agenda": "Schedule",
    "dashboard.health": "Health",
    "dashboard.pendingVaccines": "Pending Vaccines",
    "dashboard.scheduleVaccine": "Schedule Vaccine",
    "desinformacion.articlesHeading": "Informational articles about pets",
    "desinformacion.sessionsEyebrow": "Sessions",
    "desinformacion.upcomingSessions": "Upcoming vaccination days",
    "desinformacion.readMore": "Read more",
    "desinformacion.viewDetails": "View details",
    "desinformacion.vaccinationDayPrefix": "Vaccination Day",
    "desinformacion.article.basicCare.title": "Basic care for your dog",
    "desinformacion.article.basicCare.body": "Balanced nutrition, fresh water at all times, daily walks, and regular vet checkups are the foundation of your dog's wellbeing. Keep vaccines and deworming up to date.",
    "desinformacion.article.nutrition.title": "Healthy nutrition",
    "desinformacion.article.nutrition.body": "A balanced diet suited to your pet's age, size, and activity level prevents illness and improves quality of life. Avoid feeding them human food with salt, sugar, or seasoning.",
    "desinformacion.article.exercise.title": "The importance of exercise",
    "desinformacion.article.exercise.body": "Daily exercise helps control weight, reduces anxiety, and strengthens your bond with your pet. Adjust intensity and duration to their breed, age, and physical condition.",
    "desinformacion.article.understandingPet.title": "How to understand your pet",
    "desinformacion.article.understandingPet.body": "Body language, barks, meows, and posture tell you a lot about how your pet feels. Learning to read these signals strengthens communication and prevents behavior problems.",
    "desinformacion.article.vaccines.title": "Essential vaccines",
    "desinformacion.article.vaccines.body": "Vaccines protect your pet from serious, contagious diseases. Check with your vet for the right vaccination schedule based on species, age, and lifestyle.",
    "desinformacion.article.warningSigns.title": "Warning signs in pets",
    "desinformacion.article.warningSigns.body": "Loss of appetite, lethargy, frequent vomiting, or sudden behavior changes can signal something is wrong. When in doubt, see a vet as soon as possible.",
    "desinformacion.jornada.sanMiguelito.date": "June 15, 2026",
    "desinformacion.jornada.sanMiguelito.location": "Los Andes Park",
    "desinformacion.jornada.sanMiguelito.description": "Free rabies vaccination and deworming clinic for dogs and cats.",
    "desinformacion.jornada.laChorrera.date": "June 22, 2026",
    "desinformacion.jornada.laChorrera.location": "Central Plaza",
    "desinformacion.jornada.laChorrera.description": "General vaccination and basic veterinary checkups at no cost for your pet.",
    "desinformacion.jornada.arraijan.date": "June 29, 2026",
    "desinformacion.jornada.arraijan.location": "Municipal Field",
    "desinformacion.jornada.arraijan.description": "Rabies vaccination day open to the whole community.",
    "todo.taskPending": "task pending",
    "todo.tasksPending": "tasks pending",
    "calendar.smartReminders": "Smart reminders",
    "calendar.loading": "Loading...",
    "calendar.nothingPending": "Nothing due in the next 7 days. 🎉",
    "calendar.today": "Today",
    "calendar.inPrefix": "In",
    "calendar.daySingular": "day",
    "calendar.dayPlural": "days",
    "calendar.nextDoseLabel": "Next dose:",
    "calendar.aboutBefore": "This calendar automatically combines your vet appointments, upcoming vaccine doses, and reminders for",
    "calendar.aboutAfter": ", giving you a heads-up before anything comes due.",
    "alertaPaw.subtitle": "Pets reported lost in the community.",
    "alertaPaw.reportButton": "Report a lost pet",
    "alertaPaw.loading": "Loading alerts...",
    "alertaPaw.empty": "No active alerts right now.",
    "denuncias.categoryAbuse": "Animal abuse",
    "denuncias.categoryAbandonment": "Abandonment",
    "denuncias.categoryIllegalSale": "Illegal sale",
    "denuncias.categoryOther": "Other",
    "denuncias.describeBeforeSend": "Describe the situation before sending",
    "denuncias.submitError": "Couldn't send the report. Please try again.",
    "denuncias.sentTitle": "Report sent",
    "denuncias.sentBody": "Thanks for reporting it. Your identity is never stored.",
    "denuncias.goBack": "Back",
    "denuncias.anonymousTitle": "100% Anonymous",
    "denuncias.anonymousBody": "We never ask for or store your name, email, or any identifying information.",
    "denuncias.reportType": "Report type",
    "denuncias.descriptionLabel": "Description",
    "denuncias.descriptionPlaceholder": "Describe what you observed in as much detail as possible",
    "denuncias.locationLabel": "Location (optional)",
    "denuncias.locationPlaceholder": "Address or landmark",
    "denuncias.cityLabel": "City (optional)",
    "denuncias.cityPlaceholder": "City",
    "denuncias.cancel": "Cancel",
    "denuncias.submitting": "Sending...",
    "denuncias.submit": "Send report",
    "community.savedLocally": "Saved locally (backend not available in this preview)",
    "community.draftPlaceholderBefore": "What's",
    "community.draftPlaceholderAfter": "up to today?",
    "community.postButton": "Post",
    "community.loading": "Loading community...",
    "community.empty": "Be the first to share a moment with your pet 🐾",
    "community.with": "with",
    "community.commentPlaceholder": "Write a comment...",
    "community.send": "Send",
    "community.offlineNotice": "Couldn't connect to the backend — showing the community in local mode. Once the server is deployed, this syncs for everyone.",
    "petMoments.age": "years old",
    "petMoments.statMoments": "Moments",
    "petMoments.statLikes": "Likes",
    "petMoments.statFollowers": "Followers",
    "petMoments.recentMoments": "Recent moments",
    "petMoments.viewAlbums": "View albums",
    "petMoments.myAlbums": "My albums",
    "petMoments.toastCreateSoon": "You'll be able to create new albums soon",
    "petMoments.newAlbum": "New album",
    "petMoments.noAlbumsTitle": "No albums yet",
    "petMoments.createFirstAlbumBefore": "Create your first album and upload photos of",
    "petMoments.toastCreateUploadSoon": "You'll be able to create albums and upload photos soon",
    "petMoments.createAlbum": "Create album",
    "petMoments.photosSuffix": "photos",
    "petMoments.optionsForBefore": "Options for",
    "petMoments.optionsForAfter": "coming soon",
    "petMoments.backToAlbums": "Back to my albums",
    "petMoments.prevPage": "Previous page",
    "petMoments.nextPage": "Next page",
    "petMoments.soulfulMoments": "Moments that fill the heart 💜",
    "petMoments.happyDayNote": "What a happy day! 🐾",
  },
  es: {
    "app.title": "Pet Nova",
    "app.subtitle": "Comunidad de Cuidado de Mascotas",
    "nav.weCare": "We Care",
    "nav.inMyPet": "In My Pet",
    "nav.action": "Acción",
    "nav.smartCalendar": "Paw Planner",
    "nav.petMap": "Mapa Pet",
    "nav.viewProfile": "Ver Perfil",
    "nav.myPets": "Mis Mascotas",
    "nav.settings": "Configuración",
    "nav.logout": "Cerrar Sesión",
    "nav.todo": "Por Hacer",
    "nav.home": "Home",
    "nav.desinformacion": "Desinformación",
    "nav.desorganizacion": "Desorganización",
    "nav.alertaPaw": "Alerta Paw",
    "nav.denunciasAnonimas": "Denuncias Anónimas",
    "nav.infoSite": "We Care",
    "nav.vaccinationDays": "Jornadas de Vacunación",
    "nav.myPetCommunity": "My Pet Community",
    "nav.petMoments": "Pet Moments",
    "todo.title": "Por Hacer",
    "todo.subtitle": "Tareas pendientes de tu mascota",
    "todo.addPlaceholder": "Nueva tarea...",
    "todo.dueDate": "Fecha límite (opcional)",
    "todo.add": "Agregar",
    "todo.all": "Todas",
    "todo.pending": "Pendientes",
    "todo.done": "Hechas",
    "todo.empty": "No hay tareas aquí.",
    "todo.clearDone": "Borrar completadas",
    "calendar.viewMonth": "Mes",
    "calendar.viewList": "Lista",
    "calendar.filterAll": "Todo",
    "calendar.filterAppointments": "Citas",
    "calendar.filterVaccines": "Vacunas",
    "calendar.filterReminders": "Recordatorios",
    "calendar.addReminder": "Agregar recordatorio",
    "calendar.reminderPlaceholder": "Título del recordatorio...",
    "calendar.thisMonth": "Este mes",
    "calendar.noDay": "Sin eventos este día para",
    "theme.light": "Modo claro",
    "theme.dark": "Modo oscuro",
    "login.welcome": "Bienvenido de nuevo",
    "login.subtitle": "Inicia sesión en Pet Nova",
    "login.email": "Correo",
    "login.password": "Contraseña",
    "login.rememberPassword": "Recordar contraseña",
    "login.submit": "Iniciar sesión",
    "login.submitting": "Ingresando...",
    "login.invalidCredentials": "Ingresa un correo y contraseña válidos",
    "login.welcomeToast": "¡Bienvenido de nuevo!",
    "login.failed": "No se pudo iniciar sesión. ¿Está corriendo el backend?",
    "registration.title": "Únete a Pet Nova",
    "registration.subtitle": "Registra tu mascota en menos de dos minutos",
    "registration.step1": "Paso 1 · Perfil de Mascota",
    "registration.step2": "Paso 2 · Historial Médico",
    "registration.step3": "Paso 3 · Datos del Propietario",
    "registration.petName": "Nombre de la Mascota",
    "registration.species": "Especie",
    "registration.age": "Edad (años)",
    "registration.breed": "Raza",
    "registration.weight": "Peso",
    "registration.unit": "Unidad",
    "registration.photo": "Foto",
    "registration.uploadPhoto": "Subir Foto",
    "registration.vaccinated": "¿Vacunado?",
    "registration.disability": "¿Condición Especial?",
    "registration.disabilityDetail": "Describe",
    "registration.medicalNotes": "Notas Médicas",
    "registration.ownerName": "Nombre Completo",
    "registration.email": "Email",
    "registration.phone": "Teléfono",
    "registration.city": "Ciudad",
    "registration.next": "Siguiente",
    "registration.back": "Atrás",
    "registration.register": "Registrarse",
    "registration.haveAccount": "¿Ya tienes cuenta?",
    "registration.loginLink": "Inicia sesión",
    "registration.password": "Contraseña",
    "registration.confirmPassword": "Confirmar contraseña",
    "registration.passwordPlaceholder": "Mínimo 6 caracteres",
    "registration.confirmPasswordPlaceholder": "Repite la contraseña",
    "registration.passwordMinLength": "La contraseña debe tener al menos 6 caracteres",
    "registration.passwordMismatch": "Las contraseñas no coinciden",
    "registration.emailExists": "Ya existe una cuenta con ese correo",
    "registration.creatingAccount": "Creando cuenta...",
    "authSwitch.login": "Iniciar sesión",
    "authSwitch.register": "Crear cuenta",
    "authSwitch.ariaLabel": "Alternar entre iniciar sesión y crear cuenta",
    "dashboard.hello": "Hola",
    "dashboard.welcome": "Bienvenido al",
    "dashboard.panel": "panel",
    "dashboard.appointments": "Citas",
    "dashboard.vaccines": "Vacunas",
    "dashboard.alerts": "Alertas Activas",
    "dashboard.city": "Ciudad",
    "dashboard.scheduleAppointment": "Agendar Cita",
    "dashboard.date": "Fecha",
    "dashboard.time": "Hora",
    "dashboard.type": "Tipo",
    "dashboard.veterinarian": "Veterinario",
    "dashboard.notes": "Notas",
    "dashboard.schedule": "Agendar",
    "dashboard.upcomingAppointments": "Próximas Citas",
    "dashboard.noAppointments": "No hay citas agendadas",
    "dashboard.registerVaccine": "Registrar Vacuna",
    "dashboard.vaccineName": "Nombre de la Vacuna",
    "dashboard.applicationDate": "Fecha de Aplicación",
    "dashboard.nextDue": "Próxima Dosis",
    "dashboard.vaccineHistory": "Historial de Vacunas",
    "dashboard.noVaccines": "No hay vacunas registradas",
    "dashboard.createAlert": "Crear Alerta Paw",
    "dashboard.location": "Ubicación",
    "dashboard.description": "Descripción",
    "dashboard.contact": "Tu Contacto",
    "dashboard.publishAlert": "Publicar Alerta",
    "dashboard.communityAlerts": "Alertas de la Comunidad",
    "dashboard.noAlerts": "No hay alertas activas",
    "settings.title": "Configuración",
    "settings.account": "Cuenta",
    "settings.email": "Correo",
    "settings.password": "Contraseña",
    "settings.preferences": "Preferencias",
    "settings.theme": "Tema",
    "common.cancel": "Cancelar",
    "settings.language": "Idioma",
    "settings.profile": "Perfil",
    "settings.privacy": "Privacidad",
    "settings.about": "Acerca de",
    "map.title": "Huellitas al Camino",
    "map.veterinarians": "Veterinarias",
    "map.parks": "Parques",
    "map.groomers": "Aseo",
    "map.lostPets": "Mascotas Perdidas",
    "toast.success": "Éxito",
    "toast.error": "Error",
    "toast.required": "Por favor completa todos los campos",
    "app.logoAlt": "Pet Nova - Cuidamos lo que amas",
    "dashboard.overview": "Panel",
    "dashboard.agenda": "Agenda",
    "dashboard.health": "Salud",
    "dashboard.pendingVaccines": "Vacunas Pendientes",
    "dashboard.scheduleVaccine": "Agendar Vacuna",
    "desinformacion.articlesHeading": "Artículos informativos sobre mascotas",
    "desinformacion.sessionsEyebrow": "Jornadas",
    "desinformacion.upcomingSessions": "Próximas jornadas de vacunación",
    "desinformacion.readMore": "Leer más",
    "desinformacion.viewDetails": "Ver detalles",
    "desinformacion.vaccinationDayPrefix": "Jornada de Vacunación",
    "desinformacion.article.basicCare.title": "Cuidados básicos para tu perro",
    "desinformacion.article.basicCare.body": "Alimentación balanceada, agua fresca disponible siempre, paseos diarios y visitas periódicas al veterinario son la base del bienestar de tu perro. No olvides mantener al día sus vacunas y desparasitaciones.",
    "desinformacion.article.nutrition.title": "Alimentación saludable",
    "desinformacion.article.nutrition.body": "Una dieta equilibrada según la edad, tamaño y nivel de actividad de tu mascota previene enfermedades y mejora su calidad de vida. Evita darle comida humana con sal, azúcar o condimentos.",
    "desinformacion.article.exercise.title": "La importancia del ejercicio",
    "desinformacion.article.exercise.body": "El ejercicio diario ayuda a controlar el peso, reduce la ansiedad y fortalece el vínculo con tu mascota. Adapta la intensidad y duración a su raza, edad y condición física.",
    "desinformacion.article.understandingPet.title": "Cómo entender a tu mascota",
    "desinformacion.article.understandingPet.body": "El lenguaje corporal, los ladridos, maullidos y la postura de tu mascota comunican mucho sobre cómo se siente. Aprender a leer estas señales fortalece la comunicación y previene problemas de comportamiento.",
    "desinformacion.article.vaccines.title": "Vacunas esenciales",
    "desinformacion.article.vaccines.body": "Las vacunas protegen a tu mascota de enfermedades graves y contagiosas. Consulta con tu veterinario el esquema de vacunación adecuado según su especie, edad y estilo de vida.",
    "desinformacion.article.warningSigns.title": "Señales de alerta en mascotas",
    "desinformacion.article.warningSigns.body": "Pérdida de apetito, letargo, vómitos frecuentes o cambios bruscos de comportamiento pueden ser señales de que algo no está bien. Ante cualquier duda, consulta a un veterinario cuanto antes.",
    "desinformacion.jornada.sanMiguelito.date": "15 de junio 2026",
    "desinformacion.jornada.sanMiguelito.location": "Parque Los Andes",
    "desinformacion.jornada.sanMiguelito.description": "Jornada gratuita de vacunación antirrábica y desparasitación para perros y gatos.",
    "desinformacion.jornada.laChorrera.date": "22 de junio 2026",
    "desinformacion.jornada.laChorrera.location": "Plaza Central",
    "desinformacion.jornada.laChorrera.description": "Vacunación general y control veterinario básico sin costo para tu mascota.",
    "desinformacion.jornada.arraijan.date": "29 de junio 2026",
    "desinformacion.jornada.arraijan.location": "Cancha Municipal",
    "desinformacion.jornada.arraijan.description": "Jornada de vacunación antirrábica abierta a toda la comunidad.",
    "todo.taskPending": "tarea pendiente",
    "todo.tasksPending": "tareas pendientes",
    "calendar.smartReminders": "Recordatorios inteligentes",
    "calendar.loading": "Cargando...",
    "calendar.nothingPending": "No hay nada pendiente en los próximos 7 días. 🎉",
    "calendar.today": "Hoy",
    "calendar.inPrefix": "En",
    "calendar.daySingular": "día",
    "calendar.dayPlural": "días",
    "calendar.nextDoseLabel": "Próxima dosis:",
    "calendar.aboutBefore": "Este calendario combina automáticamente tus citas veterinarias, las próximas dosis de vacunas y tus recordatorios propios de",
    "calendar.aboutAfter": ", y te avisa con anticipación cuando algo se acerca.",
    "alertaPaw.subtitle": "Mascotas reportadas como perdidas en la comunidad.",
    "alertaPaw.reportButton": "Reportar mascota perdida",
    "alertaPaw.loading": "Cargando alertas...",
    "alertaPaw.empty": "No hay alertas activas por ahora.",
    "denuncias.categoryAbuse": "Maltrato animal",
    "denuncias.categoryAbandonment": "Abandono",
    "denuncias.categoryIllegalSale": "Venta ilegal",
    "denuncias.categoryOther": "Otro",
    "denuncias.describeBeforeSend": "Describe la situación antes de enviar",
    "denuncias.submitError": "No se pudo enviar la denuncia. Intenta de nuevo.",
    "denuncias.sentTitle": "Denuncia enviada",
    "denuncias.sentBody": "Gracias por reportarlo. Tu identidad no se guarda en ningún momento.",
    "denuncias.goBack": "Volver",
    "denuncias.anonymousTitle": "100% anónimo",
    "denuncias.anonymousBody": "No se solicita ni se guarda tu nombre, correo o cualquier dato que te identifique.",
    "denuncias.reportType": "Tipo de denuncia",
    "denuncias.descriptionLabel": "Descripción",
    "denuncias.descriptionPlaceholder": "Describe lo que observaste con el mayor detalle posible",
    "denuncias.locationLabel": "Ubicación (opcional)",
    "denuncias.locationPlaceholder": "Dirección o punto de referencia",
    "denuncias.cityLabel": "Ciudad (opcional)",
    "denuncias.cityPlaceholder": "Ciudad",
    "denuncias.cancel": "Cancelar",
    "denuncias.submitting": "Enviando...",
    "denuncias.submit": "Enviar denuncia",
    "community.savedLocally": "Guardado localmente (backend no disponible en esta vista previa)",
    "community.draftPlaceholderBefore": "¿Qué está haciendo",
    "community.draftPlaceholderAfter": "hoy?",
    "community.postButton": "Publicar",
    "community.loading": "Cargando comunidad...",
    "community.empty": "Sé el primero en compartir un momento con tu mascota 🐾",
    "community.with": "con",
    "community.commentPlaceholder": "Escribe un comentario...",
    "community.send": "Enviar",
    "community.offlineNotice": "No se pudo conectar al backend — mostrando la comunidad en modo local. Al desplegar el servidor esto se sincroniza para todos.",
    "petMoments.age": "años",
    "petMoments.statMoments": "Momentos",
    "petMoments.statLikes": "Me gusta",
    "petMoments.statFollowers": "Seguidores",
    "petMoments.recentMoments": "Momentos recientes",
    "petMoments.viewAlbums": "Ver álbumes",
    "petMoments.myAlbums": "Mis álbumes",
    "petMoments.toastCreateSoon": "Muy pronto vas a poder crear nuevos álbumes",
    "petMoments.newAlbum": "Nuevo álbum",
    "petMoments.noAlbumsTitle": "Aún no hay álbumes",
    "petMoments.createFirstAlbumBefore": "Creá tu primer álbum y subí las fotos de",
    "petMoments.toastCreateUploadSoon": "Muy pronto vas a poder crear álbumes y subir fotos",
    "petMoments.createAlbum": "Crear álbum",
    "petMoments.photosSuffix": "fotos",
    "petMoments.optionsForBefore": "Opciones de",
    "petMoments.optionsForAfter": "próximamente",
    "petMoments.backToAlbums": "Volver a mis álbumes",
    "petMoments.prevPage": "Página anterior",
    "petMoments.nextPage": "Página siguiente",
    "petMoments.soulfulMoments": "Momentos que llenan el alma 💜",
    "petMoments.happyDayNote": "¡Qué día tan feliz! 🐾",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const stored = sessionStorage.getItem("petNovaLanguage");
      return (stored as Language) || "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    sessionStorage.setItem("petNovaLanguage", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations["en"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
